---

- name: Kubernetes
  hosts: gce
  connection: ssh

  tasks:
  - name: Installing from https://get.k8s.io
    command: export KUBERNETES_PROVIDER=gce; wget -q -O - https://get.k8s.io | bash

  - name: Installing kubectl
    command: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl > kubectl

  - name: Changing Permissions
    command: chmod 750 kubectl

  - name: Setting up kubeconfig
    command: export KUBECONFIG=~/.kube/config

  - name: Changing kubectl path
    command: mv kubectl /usr/local/bin/
